/**
 * Daily quest catalog seeded into MongoDB and sampled for each user per day.
 * Every quest must have a `trackKey` the app can detect and auto-complete.
 */

const DAILY_QUEST_CATALOG = [
  // ── Check-in ──────────────────────────────────────────────────────────────
  {
    title: "Complete today's check-in",
    description: "Finish your daily wellbeing chat once today.",
    rewardPoints: 10,
    category: "checkin",
    trackKey: "checkin.complete",
  },
  {
    title: "Finish your wellbeing check-in",
    description: "Go through today's check-in flow from start to finish.",
    rewardPoints: 10,
    category: "checkin",
    trackKey: "checkin.complete",
  },
  {
    title: "Check in with yourself",
    description: "Complete one full wellbeing check-in today.",
    rewardPoints: 10,
    category: "checkin",
    trackKey: "checkin.complete",
  },
  {
    title: "Start your daily check-in",
    description: "Wrap up your wellbeing chat for today.",
    rewardPoints: 8,
    category: "checkin",
    trackKey: "checkin.complete",
  },
  {
    title: "Review your check-in summary",
    description: "Open your summary after finishing today's check-in.",
    rewardPoints: 6,
    category: "checkin",
    trackKey: "checkin.summary",
  },
  {
    title: "Read how you're doing",
    description: "View your check-in summary screen today.",
    rewardPoints: 6,
    category: "checkin",
    trackKey: "checkin.summary",
  },
  {
    title: "See your wellbeing results",
    description: "Open the summary that follows your check-in.",
    rewardPoints: 5,
    category: "checkin",
    trackKey: "checkin.summary",
  },
  {
    title: "Keep your streak alive",
    description: "Check in on a day when your streak is still going.",
    rewardPoints: 8,
    category: "checkin",
    trackKey: "checkin.streak",
  },
  {
    title: "Extend your daily streak",
    description: "Complete a check-in to grow your streak.",
    rewardPoints: 8,
    category: "checkin",
    trackKey: "checkin.streak",
  },
  {
    title: "Don't break the chain",
    description: "Check in while your streak is active.",
    rewardPoints: 7,
    category: "checkin",
    trackKey: "checkin.streak",
  },

  // ── Mood ────────────────────────────────────────────────────────────────────
  {
    title: "Pick your mood",
    description: "Choose how you feel on the homepage mood strip.",
    rewardPoints: 5,
    category: "checkin",
    trackKey: "mood.select",
  },
  {
    title: "Set how you feel today",
    description: "Select a mood on the Home screen.",
    rewardPoints: 5,
    category: "checkin",
    trackKey: "mood.select",
  },
  {
    title: "Update your mood",
    description: "Tap a mood face to log how you're doing.",
    rewardPoints: 5,
    category: "checkin",
    trackKey: "mood.select",
  },
  {
    title: "Log your mood for today",
    description: "Choose a mood on the homepage.",
    rewardPoints: 4,
    category: "checkin",
    trackKey: "mood.select",
  },

  // ── Social: messaging ─────────────────────────────────────────────────────
  {
    title: "Send a supportive message",
    description: "Send one message to a friend in chat.",
    rewardPoints: 5,
    category: "social",
    trackKey: "social.message",
  },
  {
    title: "Talk to a friend",
    description: "Send a chat message to someone on your friends list.",
    rewardPoints: 5,
    category: "social",
    trackKey: "social.message",
  },
  {
    title: "Reach out today",
    description: "Say hello to a friend in chat.",
    rewardPoints: 5,
    category: "social",
    trackKey: "social.message",
  },
  {
    title: "Send a chat message",
    description: "Write and send one message in a friend chat.",
    rewardPoints: 4,
    category: "social",
    trackKey: "social.message",
  },
  {
    title: "Check in on a friend",
    description: "Send a message to let a friend know you're thinking of them.",
    rewardPoints: 6,
    category: "social",
    trackKey: "social.message",
  },
  {
    title: "Reply to a friend",
    description: "Respond to a message using the reply action.",
    rewardPoints: 6,
    category: "social",
    trackKey: "social.reply",
  },
  {
    title: "Answer a friend's message",
    description: "Use reply on a chat message today.",
    rewardPoints: 5,
    category: "social",
    trackKey: "social.reply",
  },
  {
    title: "Keep the conversation going",
    description: "Reply to something a friend sent you.",
    rewardPoints: 5,
    category: "social",
    trackKey: "social.reply",
  },
  {
    title: "Protect your messaging streak",
    description: "Send a message when a friend streak is at risk.",
    rewardPoints: 8,
    category: "social",
    trackKey: "social.streak.keep",
  },
  {
    title: "Save a friend streak",
    description: "Message a friend before their streak resets.",
    rewardPoints: 8,
    category: "social",
    trackKey: "social.streak.keep",
  },
  {
    title: "Keep a flame alive",
    description: "Send a chat message to protect an active streak.",
    rewardPoints: 7,
    category: "social",
    trackKey: "social.streak.keep",
  },
  {
    title: "Open a friend chat",
    description: "Visit a friend's chat screen today.",
    rewardPoints: 4,
    category: "social",
    trackKey: "social.chat.open",
  },
  {
    title: "Drop by a friend's chat",
    description: "Open any friend conversation from the Friends tab.",
    rewardPoints: 4,
    category: "social",
    trackKey: "social.chat.open",
  },

  // ── Social: friends ───────────────────────────────────────────────────────
  {
    title: "Grow your circle",
    description: "Send a friend request using a friend code.",
    rewardPoints: 8,
    category: "social",
    trackKey: "social.friend.add",
  },
  {
    title: "Add a new friend",
    description: "Send a friend request from the Friends screen.",
    rewardPoints: 8,
    category: "social",
    trackKey: "social.friend.add",
  },
  {
    title: "Connect with someone new",
    description: "Use a friend code to send a request.",
    rewardPoints: 7,
    category: "social",
    trackKey: "social.friend.add",
  },
  {
    title: "Accept a friend request",
    description: "Approve an incoming friend request.",
    rewardPoints: 8,
    category: "social",
    trackKey: "social.friend.accept",
  },
  {
    title: "Welcome a new friend",
    description: "Accept someone who wants to connect.",
    rewardPoints: 7,
    category: "social",
    trackKey: "social.friend.accept",
  },
  {
    title: "Say yes to a request",
    description: "Accept a pending friend request today.",
    rewardPoints: 6,
    category: "social",
    trackKey: "social.friend.accept",
  },

  // ── Reflection (in-app check-in actions) ──────────────────────────────────
  {
    title: "Answer wellbeing questions",
    description: "Respond to at least one question during check-in.",
    rewardPoints: 6,
    category: "reflection",
    trackKey: "reflection.checkin_answer",
  },
  {
    title: "Reflect during check-in",
    description: "Answer a wellbeing prompt in today's check-in.",
    rewardPoints: 6,
    category: "reflection",
    trackKey: "reflection.checkin_answer",
  },
  {
    title: "Share in your check-in chat",
    description: "Type a message during the wellbeing chat.",
    rewardPoints: 7,
    category: "reflection",
    trackKey: "reflection.checkin_chat",
  },
  {
    title: "Write about your day",
    description: "Send a text reply in the check-in conversation.",
    rewardPoints: 7,
    category: "reflection",
    trackKey: "reflection.checkin_chat",
  },
  {
    title: "Open your check-in summary",
    description: "Review the summary after your wellbeing chat.",
    rewardPoints: 5,
    category: "reflection",
    trackKey: "checkin.summary",
  },

  // ── Profile & app navigation ──────────────────────────────────────────────
  {
    title: "Visit your wardrobe",
    description: "Open the wardrobe screen from Home.",
    rewardPoints: 4,
    category: "checkin",
    trackKey: "profile.wardrobe.visit",
  },
  {
    title: "Style your mascot",
    description: "Open wardrobe to preview your look.",
    rewardPoints: 4,
    category: "checkin",
    trackKey: "profile.wardrobe.visit",
  },
  {
    title: "Try a new color theme",
    description: "Change your app color theme in settings.",
    rewardPoints: 5,
    category: "checkin",
    trackKey: "profile.theme.change",
  },
  {
    title: "Switch your theme",
    description: "Pick a different color theme in settings.",
    rewardPoints: 5,
    category: "checkin",
    trackKey: "profile.theme.change",
  },
  {
    title: "Check your notifications",
    description: "Open the notifications panel on Home.",
    rewardPoints: 4,
    category: "checkin",
    trackKey: "app.notifications.read",
  },
  {
    title: "See what's new",
    description: "Open notifications to catch up on activity.",
    rewardPoints: 4,
    category: "checkin",
    trackKey: "app.notifications.read",
  },
];

module.exports = { DAILY_QUEST_CATALOG };
